### ISSUE TITLE
ValueError: non-hexadecimal number found in fromhex() arg at position 8

### ISSUE THREAD

**Issue by spmckenney** [DevvioInc/Devv-Core#3]
While running mini-client-v0.1.7 / devvio-inn-2dd19cd66 at test.devv.io, the following exception occurred (addresses and keys sanitized):

`
15-10-2018:17:47:59,575 INFO     [__init__.py:120] sig: AAAAA
15-10-2018:17:47:59,575 INFO     [__init__.py:121] wallet: BBBBB
15-10-2018:17:47:59,576 INFO     [__init__.py:122] to: 00000000-0000-0000-0000-000000000000
15-10-2018:17:47:59,576 INFO     [__init__.py:123] coin: 0
15-10-2018:17:47:59,576 INFO     [__init__.py:124] amount: 1
15-10-2018:17:47:59,576 INFO     [__init__.py:125] hex: 740000000000000008000000000000000221039b464366728845e4238558dfc8c8c0e696061a9d6a186618e89fcc80ca0fad650000000000000000ffffffffffffffff000000000000000021000
00000-0000-0000-0000-000000000000000000000000000001000000000000000000000000000000d1d2c45b00000000493044022037721c62ef954a2009d49ce3f8425887cf289eb960edb763d208ef77b4707e0402207f1d698da5b4ca7d5d3505b9194205bcd7bf
19645b41c4e20d1d763e4ee7101a000000
15-10-2018:17:47:59,577 DEBUG    [db.py:158] wallet_addr: XXXXX
15-10-2018:17:47:59,577 DEBUG    [__init__.py:140] wallet_addr: XXXXX
15-10-2018:17:47:59,578 DEBUG    [__init__.py:156] Got a key!! YYYYY
Created nonce from string value
15-10-2018:17:47:59,579 DEBUG    [__init__.py:40] len(tx._transfers): 0
Adding transfer: XXXXX:0:-1:0
Transfer: XXXXX:0:-1:0
Adding transfer: 00000000-0000-0000-0000-000000000000:0:1:0
Transfer: 00000000-0000-0000-0000-000000000000:0:1:0
15-10-2018:17:47:59,587 INFO     [_internal.py:88] 172.17.0.1 - - [15/Oct/2018 17:47:59] "POST /send_tx HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/app.py", line 2308, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/app.py", line 2294, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/app.py", line 1739, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/app.py", line 2291, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/app.py", line 1814, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/app.py", line 1812, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/dcrunner/py_virtual_env/devvio-inn/src/flask/flask/app.py", line 1798, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/dcrunner/devcash/devvio-inn/inn/controller/handlers.py", line 55, in send_tx
    return control.send_tx(request)
  File "/opt/dcrunner/devcash/devvio-inn/inn/controller/__init__.py", line 168, in send_tx
    dbfunc=self.db.send_tx)
  File "/opt/dcrunner/devcash/devvio-inn/inn/controller/__init__.py", line 42, in submit_transaction
    tx.add_transfer(recipient, coin, amount, 0)
  File "/opt/dcrunner/devcash/devcash-core/examples/python/devv/devv.py", line 90, in add_transfer
    self._transfers.append(DevvTransfer(address=address, coin=coin, amount=amount, delay=delay))
  File "/opt/dcrunner/devcash/devcash-core/examples/python/devv/devv.py", line 33, in __init__
    self._address = bytes.fromhex(address)
ValueError: non-hexadecimal number found in fromhex() arg at position 8
`

**Comment by noncist** [comment]
have we already addressed this?  My guess would be there's a uuid where it expects a public key in hex.
